# Generated by Django 3.1.6 on 2021-02-10 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.CharField(default=1, max_length=50, verbose_name='料金'),
            preserve_default=False,
        ),
    ]
