# Generated by Django 2.2.18 on 2021-02-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210212_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='イメージ画像'),
        ),
    ]
