# Generated by Django 2.2.18 on 2021-02-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_post_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='URL'),
        ),
    ]
