# Generated by Django 2.2.18 on 2021-02-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20210219_0642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='イメージ画像')),
                ('name', models.CharField(max_length=20, verbose_name='タイトル')),
                ('comment', models.TextField(verbose_name='内容')),
            ],
        ),
    ]
