# Generated by Django 2.2.18 on 2021-02-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='icon', verbose_name='イメージ画像'),
        ),
    ]
